### ISSUE TITLE
Hamburger Menu doesn't work

### ISSUE THREAD

**Issue by AlexAtmo** [3liz/lizmap-javascript-scripts#38]
Hello,

I'm currently trying to customize some web apps and I just found out that you could add some js and css directly into a media folder. I tried several useful scripts here but I have some problems with the hamburger menu.

As I put the .js into the right folder, _media/js/myproject/**add_hamburger_menu.js**_ , the UI loses nearly all buttons, for both mobile and deskop interface. However, the geolocation seems to work so I'm kind of lost. 

I saw that there was a specific theme too, so I put it into _media/themes/myproject/css/**add_hamburger_menu.css**_ , but maybe I need to put it into one of the "css" default files found thanks to the [lizmap documentation](https://docs.lizmap.com/current/en/publish/customization/themes.html?highlight=themes) ?

thanks for the help

**Comment by Gustry** [comment]
Hamburger menu is deprecated since LWc 3.4. This should reflected in the readme.md but it hasn't been done yet.
Which LWC version are you using ?

**Comment by AlexAtmo** [comment]
I'm still using the 3.3 but since we're planning to update LWC to 3.4 soon I guess you answered pretty much my question.

I will stay in put in case a new version comes out, thank you !
