### ISSUE TITLE
activateSnapWhenEditing

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-javascript-scripts#5]
hi @mdouchin 

great!!!

i have tried to duplicate the script file for "SousQuartiers" layer, and it works for both layers (Quartiers and SousQuartiers). but when i clone the script file on more time for "areas_of_interest", the snapping only works for "areas_of_interest"... i don´t know why

thanks for your work :-)

**Comment by mdouchin** [comment]
It has been made for only one layer. If you duplicate the file, it won't work.

We could instead have an array of source layers, and iterate through them to get all needed features.

Or you could in the meantime use a view or QGIS virtual layers to put all the needed geometries in one single source layer.

**Comment by rldhont** [comment]
The enhancement has been done and fixed https://github.com/3liz/lizmap-javascript-scripts/commit/1ff41eeba74b8621e9cd81b80f43911b6f8b3f4e
