### ISSUE TITLE
How to add a download button

### ISSUE THREAD

**Issue by androidtv160987** [3liz/lizmap-javascript-scripts#53]
![image](https://user-images.githubusercontent.com/75124133/178142552-80919e7b-06ed-4189-b882-1197fc3897ba.png)

How to create a button for donwload my project?

**Comment by ygorigor** [comment]
This is the script from that page 
[Script](https://demo.lizmap.com/lizmap/index.php/view/media/getMedia?repository=feat1&project=lampadaires&mtime=1614785127&path=media%2Fjs%2Flampadaires%2F_download.js)

**Comment by Gustry** [comment]
Thanks @ygorigor 

Indeed, you can open https://demo.lizmap.com/lizmap/index.php/view/map/?repository=feat1&project=lampadaires
Then "CTRL+U" and scroll to the last lines.
You will always find additional JS files at the end such as the one you are looking for.
