### ISSUE TITLE
Add a button to download a layer in xlsx

### ISSUE THREAD

**Issue by jserieye** [3liz/lizmap-javascript-scripts#66]
Hello, 

I am looking to add a button to export a layer (by default) in xlsl format.

The goal is to add this button in the nav nav-list to avoid the user having to open the attribute table.

Thank you.

Jérémy

**Comment by nworr** [comment]
You can use  `lizMap.exportVectorLayer(layername, exportFormat, restrictToMapExtent ) ` function 

Using the `uicreated` you can add element to nav-list and add a click listener to call the function

**Comment by Gustry** [comment]
I'm closing here, as there is already another ticket https://github.com/3liz/lizmap-web-client/issues/3956
