### ISSUE TITLE
[Bug]:monitor 4k non funziona

### ISSUE THREAD

**Issue by Sit-Mirano** [3liz/lizmap-javascript-scripts#86]
### What is the bug? (in English)

4k monitor display does not work, you are forced to reduce the resolution settings to 1920x1080

### Logs from the Javascript console

efused to load the image 'https://fonts.gstatic.com/s/i/productlogos/translate/v14/24px.svg' because it violates the following Content Security Policy directive: "img-src 'self' data: blob: github.githubassets.com media.githubusercontent.com camo.githubusercontent.com identicons.github.com avatars.githubusercontent.com private-avatars.githubusercontent.com github-cloud.s3.amazonaws.com objects.githubusercontent.com secured-user-images.githubusercontent.com/ user-images.githubusercontent.com/ private-user-images.githubusercontent.com opengraph.githubassets.com github-production-user-asset-6210df.s3.amazonaws.com customer-stories-feed.github.com spotlights-feed.github.com objects-origin.githubusercontent.com *.githubusercontent.com".

clone @ turbo.es2017-esm.js:1661
Mostra 1 altro frame
Mostra meno
new:1 Autofocus processing was blocked because a document already has a focused element.
new:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
new:1 Refused to load the stylesheet 'https://www.gstatic.com/_/translate_http/_/ss/k=translate_http.tr.26tY-h6gH9w.L.W.O/am=DAY/d=0/rs=AN8SPfrCcgxoBri2FVMQptvuOBiOsolgBw/m=el_main_css' because it violates the following Content Security Policy directive: "style-src 'unsafe-inline' github.githubassets.com". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.

36Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
gen204:1 
        
        
       
        
       Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
gen204:1 
        
        
       
        
       Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
gen204:1 
        
        
       
        
       Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
gen204:1 
        
        
       
        
       Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
gen204:1 
        
        
       
        
       Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
gen204:1 
        
        
       
        
       Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
gen204:1 
        
        
       
        
       Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
gen204:1 
        
        
       
        
       Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
gen204:1 
        
        
       
        
       Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
gen204:1 
        
        
       
        
       Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
gen204:1 
        
        
       
        
       Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
gen204:1 
    

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.0
* Lizmap plugin : 4.4.2
* QGIS Desktop : 3.34.3
* QGIS Server and plugins unknown status because the login provided is not an administrator

<details>
<summary>List of safeguards :</summary>
<br/>
* Mode : normal
* Allow parent folder : yes
* Number of parent : 2 folder(s)
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Browsers

Chrome

### Browsers version

Chrome

**Comment by Gustry** [comment]
Your issue is not linked to this repository (about custom JavaScript scripts)

> Lizmap Web Client : 3.7.0

This is very old, you must upgrade first. Some issues about 4K were fixed.
