### ISSUE TITLE
[Bug]: Possibility of displaying statistics based on entities of a layer (without using filter tool)

### ISSUE THREAD

**Issue by mjmolivo** [3liz/lizmap-javascript-scripts#89]
### What is the bug? (in English)

It is not really a bug about the scripts, I was wondering if there are any ways of showing graphs about one layer that would change depending on which polygon is being clicked on.
For example, I need to display statistics on different water basins. My water basins are gathered in a single layer "basins". But when configuring the dataviz tool implemented in the Lizmap extension for QGIS, I can't find a way to make a graph based on each of my water basins. It is displaying statistics for the whole layer.
Is there a way to filter graphs by using a JS script ?
Thanks

### Logs from the Javascript console

-

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.11
* Lizmap plugin : 4.4.4
* QGIS Desktop : 3.28.8
* Lizmap.com : Yes
* QGIS Server : 3.28.15
* Py-QGIS-Server : 1.9.1
* QGIS Server plugin DataPlotly : Not available on the "Basic" Lizmap Cloud plan
* QGIS Server plugin atlasprint : 3.4.1
* QGIS Server plugin cadastre : 1.20.0
* QGIS Server plugin lizmap_server : 2.11.2
* QGIS Server plugin wfsOutputExtension : 1.8.2

<details>
<summary>List of Lizmap Web Client modules :</summary>
<br/>
* Version Lizmap Web Client 3.8 needed
</details>

<details>
<summary>List of safeguards :</summary>
<br/>
* Mode : safe<br/>
* Allow parent folder : no<br/>
* Prevent other drive : yes<br/>
* Prevent PG service : yes<br/>
* Prevent PG Auth DB : yes<br/>
* Force PG user&pass : yes<br/>
* Prevent ECW : yes<br/>
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Browsers

Firefox

### Browsers version

Firefox 131.0.3

**Comment by mjmolivo** [comment]
Yes exactly, is the atlas tool required to solve my problem ?

**Comment by Gustry** [comment]
No at all, the "Lizmap atlas" is not linked.
Please download the demo and look.

It exactly the topic of the video tutorial : https://docs.lizmap.com/current/en/publish/lizmap_plugin/dataviz.html#video-tutorial

**Comment by mjmolivo** [comment]
Thank you very much
