### ISSUE TITLE
Google street view - base layer problem

### ISSUE THREAD

**Issue by tethysgeco** [3liz/lizmap-javascript-scripts#9]
Hi,
we are working on a lizmap project containing both google maps and openstreetmaps as baselayers and they work properly.

When we add google_street_view.js, openlayers basemap continue to be shown correctly but google basemaps doesn't work anymore (an error message is delivered, probably due to a coordinate system issue).

Do you have any ideas on how to sort things out?
Thanks

**Comment by rldhont** [comment]
I have fixing the script, can you test it ?

**Comment by tethysgeco** [comment]
Hi,
if we add google_street_view.js in a project with only OSM as basemap it works properly.

If we add it in a project with google basemaps, streetview works properly while the basemaps don't work anymore.
Maybe the problem is that the gkey are declared two times (in lizmap & in js file)? 

We tried to write only in your js:
lizMap.events.on({
    'uicreated': function(e) {
		initGoogleStreetView();
    }
});

and both google basemap and google SV works.

We think that 2 versions of js are necessary.

**Comment by josemvm** [comment]
hi @tethysgeco 

> Maybe the problem is that the gkey are declared two times (in lizmap & in js file)?

i think so

**Comment by rldhont** [comment]
fixed by https://github.com/3liz/lizmap-javascript-scripts/commit/41693dd9076fa5b384eddd5d887b419c837c59fc

**Comment by Gustry** [comment]
Can we close this one?

**Comment by rldhont** [comment]
yes fixed
